### ISSUE TITLE
separator was not removed

### ISSUE THREAD

**Issue by LaikaSa** [Ketengan-Diffusion/wdv3-batch-vit-tagger#1]
Thank you for the script, it was easy to use. However I just try it out and it seem the separators in the .txt still present, there is no error logs pop up in the terminal so I don't know what cause this. On the other note, what does the flag button do?

**Comment by tikhonlavrev** [comment]
I think I forgot to put the separators remover in the script. Wait a moment, I will fix this

**Comment by tikhonlavrev** [comment]
The remove separator should be added in latest commit

**Comment by LaikaSa** [comment]
thanks, it works now
